# Generated by Django 4.2.6 on 2024-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtime",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="meetingtime",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:30 - 11:30", "8:30 - 11:30"),
                    ("11:45 - 2:45", "11:45 - 2:45"),
                    ("3:00 - 6:00", "3:00 - 6:00"),
                    ("6:30 - 9:30", "6:30 - 9:30"),
                ],
                default="11:30 - 12:30",
                max_length=50,
            ),
        ),
    ]
