# Generated by Django 4.2.6 on 2024-03-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alter_meetingtime_day_alter_meetingtime_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtime",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:30 - 11:30", "8:30 - 11:30"),
                    ("11:45 - 2:45", "11:45 - 2:45"),
                    ("3:00 - 6:00", "3:00 - 6:00"),
                    ("6:30 - 9:30", "6:30 - 9:30"),
                ],
                default="8:30 - 11:45",
                max_length=50,
            ),
        ),
    ]
