# Generated by Django 4.2.6 on 2024-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_alter_meetingtime_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_number", models.CharField(max_length=50)),
                ("course_code", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=100)),
                ("classroom", models.CharField(max_length=50)),
                ("instructor", models.CharField(max_length=100)),
                ("class_timing", models.CharField(max_length=100)),
            ],
        ),
    ]
