# Generated by Django 4.2.6 on 2024-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="generated_pdfs/")),
            ],
        ),
    ]
