# Generated by Django 4.2.6 on 2024-03-16 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
        ("schedule", "0005_generatedschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedschedule",
            name="upload_date",
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generatedschedule",
            name="upload_time",
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generatedschedule",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.profile",
            ),
            preserve_default=False,
        ),
    ]
