# Generated by Django 4.2.6 on 2024-03-16 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0007_alter_generatedschedule_upload_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor",
            old_name="uid",
            new_name="ins_id",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="r_number",
            new_name="room_number",
        ),
    ]
