# Generated by Django 4.2.6 on 2024-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0011_delete_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_no", models.IntegerField()),
                ("course_code", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=100)),
                ("classroom", models.CharField(max_length=20)),
                ("instructor", models.CharField(max_length=100)),
                ("class_timing", models.CharField(max_length=100)),
            ],
        ),
    ]
