# Generated by Django 4.2.6 on 2024-03-18 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0012_schedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
