# Generated by Django 4.2.6 on 2024-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0013_delete_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="csv_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
